import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Footer } from './components/footer/footer'
import { Header } from './components/header/header'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
